Add JDBC device registry
eclipse/hono pull request #2159
Opened 2020-09-07 07:26 UTC by ctron

The CI is expected to fail on this one as well, as it misses changes from: https://github.com/eclipse/hono/pull/2157 and https://github.com/eclipse/hono/pull/2158

2020-09-21 11:39 UTC, ctron commented
Rebased

2020-09-24 09:10 UTC, sophokles73 reviewed
looks very good :-)

2020-09-24 09:10 UTC, sophokles73 commented on tests/pom.xml
> +                      <run>curl -sL https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar -o h2.jar</run>
can we use the version defined in `bom/POM.xml` here instead?

2020-09-24 09:10 UTC, sophokles73 commented on tests/pom.xml
> +                    <memory>524288000</memory>
this seems to be a duplicate

2020-09-24 12:34 UTC, ctron commented
Ok, I rebased, amended the feedback, and (most likely) fixes the test. Which was due to the fact that the "max bcrypt iterations" variable was renamed to "cost factor". But let's wait for travis to check.

2020-09-28 12:52 UTC, sophokles73 commented
@ctron is there anything else I can help with? FMPOV the only thing that prevents this PR from merging is the failing unit test ...

2020-09-30 09:18 UTC, fkaltner commented
> @ctron is there anything else I can help with? FMPOV the only thing that prevents this PR from being merged is the failing unit test ...

@ctron I am also happy to help, if there's anything I could do FYPOV. @dejanb would like to wait with merging the pull request for the status property (https://github.com/eclipse/hono/pull/2189) until this PR is merged...

2020-10-09 15:49 UTC, kaniyan requested changes

2020-10-09 15:49 UTC, kaniyan commented on services/device-registry-jdbc/src/main/java/org/eclipse/hono/deviceregistry/jdbc/impl/CredentialsServiceImpl.java
> +        if (!validTime(secret, CredentialsConstants.FIELD_SECRETS_NOT_AFTER, Instant::isBefore)) {
@sophokles73 @ctron 

Sorry for raising this comment now. I noticed this just now with the merge of the PR #2241 for adjusting the tests.

The Credentials API docs says:

> Adapters MUST only consider secrets for authentication which
> 
>     have their not-before property set to either null or the current or a past point in time and
>     have their not-after property set to either null or the current or a future point in time.

AFAIK the credentials API includes all the secrets irrespective of the _not-before_ & _not-after_ property. Based on the above quotes, the adapters are responsible for filtering them out. Various _AuthProvider_ implementations already do this by using `CredentialsObject.getCandidateSecrets(...)` where the secrets are already being filtered out based on the validity period. IMHO we need not filter secrets based on the validity period in the credentials API implementation. I don't think we need to adapt the tests as in #2241

2020-10-12 12:40 UTC, merged