[#2267] Add AMQP 1.0 based TenantClient implementation
eclipse/hono pull request #2277
Opened 2020-11-02 12:37 UTC by sophokles73

Added implementations of the adapter client's TenantClient interface
which simply wraps the existing vertx-proton based
"legacy" TenantClientImpl.

This is the most straight forward implementation which simply delegates all method invocations to TenantClientImpl.
This also means that caching of response messages from the Tenant service is still done inside of TenantClientImpl instances.
This might/should be improved in the future to provide caching at the ProtonBasedTenantClient level in order to be able to return caches values even if the connection/link to the service is (currently) unavailable.

2020-11-02 16:27 UTC, kaniyan requested changes

2020-11-02 16:27 UTC, kaniyan commented on clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/AbstractRequestResponseClient.java
> +     * @throws NullPointerException if any of context or configuration are {@code null}.
`@throws NullPointerException if any of context or configuration are {@code null}` doesn't reflect the actual null checks in this method. Shouldn't it be `@throws NullPointerException if any of the parameters except cacheProvider is {@code null}.`

2020-11-02 16:27 UTC, kaniyan commented on clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedTenantClient.java
> +     * @throws NullPointerException if any of the parameters are {@code null}.
_cacheProvider_ is not being null checked. In that case, it should be `@throws NullPointerException if any of the parameters except cacheProvider is {@code null}.`

2020-11-02 16:38 UTC, kaniyan commented
With this PR, `TenantClientFactoryImpl` and `TenantClientFactory` are not being used anymore (apart from `TenantAmqpIT`). Shouldn't we remove them? WDYT?

2020-11-03 08:19 UTC, sophokles73 commented on service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
> +        return context.getTenantClient().get(tenantId, null)
*org.eclipse.hono.adapter.client.registry.TenantClient* has no method accepting just the tenant ID.

2020-11-03 08:23 UTC, sophokles73 commented
@kaniyan The overall idea is to keep the *legacy* client around for some time since it is one of the components that we know are being used e.g. for implementing custom protocol adapters. We will deprecate the legacy client and remove it at a later time.

2020-11-03 08:24 UTC, kaniyan commented on service-base/src/main/java/org/eclipse/hono/service/monitoring/AbstractMessageSenderConnectionEventProducer.java
> +        return context.getTenantClient().get(tenantId, null)
Sorry, then I am mixed it up with `org.eclipse.hono.client.TenantClient`

2020-11-03 08:25 UTC, kaniyan commented
> @kaniyan The overall idea is to keep the _legacy_ client around for some time since it is one of the components that we know are being used e.g. for implementing custom protocol adapters. We will deprecate the legacy client and remove it at a later time.

:+1:

2020-11-03 08:45 UTC, sophokles73 commented
I have also removed the TenantClient.assertRegistration(String, String, SpanContext) method and instead defined the remaining variant to accept `null` as the gateway ID. This has made using the TenantClient easier because we can omit checks for an authenticated device.

@calohmn would you mind taking a look?

2020-11-03 12:11 UTC, sophokles73 commented
@kaniyan anything else that needs to be changed? If not, could you approve the PR?

2020-11-03 12:43 UTC, calohmn commented on clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/AbstractRequestResponseClient.java
> + * Copyright (c) 2016, 2019 Contributors to the Eclipse Foundation
2020

2020-11-03 12:44 UTC, calohmn commented on adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
> +    private final TenantClient tenantClientFactory;
I'd also rename this.

2020-11-03 12:46 UTC, calohmn approved these changes
LGTM (just the 2 nitpicks from the comments above)

2020-11-03 12:51 UTC, kaniyan commented on adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
> +    private final TenantClient tenantClientFactory;
> @kaniyan anything else that needs to be changed? If not, could you approve the PR?

The above comment regarding renaming the variable is still pending. But it should not hinder from merging this and its a minor one.

2020-11-03 12:51 UTC, kaniyan approved these changes

2020-11-03 13:01 UTC, sophokles73 commented on adapters/coap-vertx-base/src/main/java/org/eclipse/hono/adapter/coap/DefaultDeviceResolver.java
> +    private final TenantClient tenantClientFactory;
sure, I forgot about this one .... will rename and merge ...

2020-11-03 13:20 UTC, merged