[#2267] Add AMQP 1.0 based DeviceRegistrationClient implementation
eclipse/hono pull request #2278
Opened 2020-11-03 14:17 UTC by sophokles73

Added implementations of the adapter client's DeviceRegistrationClient
interface which simply wraps the existing vertx-proton based
"legacy" RegistrationClientImpl.

In order to be able to use the legacy CommandTargetMapper, its direct
dependency on RegistrationClientFactory and
BasicDeviceConnectionClientFactory has been replaced with a
CommandTargetMapperContext interface which provides access to the
required functionality. Existing code using the CommandTargetMapper with
the legacy client will need to be adapted. For convenience, the
CommandTargetMapper.createContext() method can be used to get an
implementation based on RegistrationClientFactory and
BasicDeviceConnectionClientFactory.

2020-11-03 16:11 UTC, sophokles73 commented
@calohmn I have pushed changes ...

2020-11-03 16:32 UTC, calohmn commented on client/src/main/java/org/eclipse/hono/client/impl/CommandTargetMapperImpl.java
>                      return Future.failedFuture(t);
The "Error getting registration assertion" log message only looks correct if one knows what `getViaGateways` is doing internally. So, "Error getting 'via' gateways" would be more obvious here.

2020-11-03 18:57 UTC, kaniyan requested changes

2020-11-03 18:57 UTC, kaniyan commented on client/src/main/java/org/eclipse/hono/client/CommandTargetMapper.java
> +     */
Missing info in JavaDoc regarding null checks.

2020-11-03 18:57 UTC, kaniyan commented on clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
> +     * @throws NullPointerException if any of the parameters are {@code null}.
`cacheProvider` is not being null checked. How about `@throws NullPointerException if any of the parameters other than cacheProvider are {@code null}.`?

2020-11-03 18:57 UTC, kaniyan commented on clients/adapter-amqp/src/main/java/org/eclipse/hono/adapter/client/registry/amqp/ProtonBasedDeviceRegistrationClient.java
> +        this.clientFactory = new CachingClientFactory<>(connection.getVertx(), c -> c.isOpen());
How about `RequestResponseClient::isOpen` instead of `c-> c.isOpen()`?

2020-11-04 08:12 UTC, sophokles73 commented
@calohmn @kaniyan I have pushed more changes ...

2020-11-04 08:33 UTC, kaniyan approved these changes
LGTM

2020-11-04 09:05 UTC, calohmn approved these changes
LGTM

2020-11-04 10:40 UTC, merged