Support configuration of MongoAuth provider
eclipse/hono pull request #2852
Opened 2021-09-14 10:15 UTC by sophokles73

The MongAuth provider used to guard access to the Mongo DB based
registry's HTTP endpoint can now be configured using environment
variables.

Fixes #2826

2021-09-14 10:48 UTC, sophokles73 commented
@kaniyan would you mind taking a look at this?

2021-09-14 16:08 UTC, kaniyan commented
> @kaniyan would you mind taking a look at this?

@sophokles73 I am back on Thursday (16.09) and sure I will take a look. It's also fine for me if someone else would like to take a look before it :)

2021-09-16 13:41 UTC, kaniyan requested changes

2021-09-16 13:41 UTC, kaniyan commented on tests/src/test/java/org/eclipse/hono/tests/CrudHttpClient.java
> +     * @param httpClientOptions The HTTP client client options to use for connecting to servers.
_client_ is mentioned twice consecutively in the _JavaDoc_.

2021-09-16 13:53 UTC, sophokles73 commented
@kaniyan I pushed a fix

2021-09-16 13:57 UTC, kaniyan approved these changes
LGTM

2021-09-16 15:01 UTC, merged